# Generated by Django 5.1.6 on 2025-02-24 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("f902bac9-db46-456a-9692-8ee7619feccf"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
