# Generated by Django 5.1.6 on 2025-02-24 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("fb4e642b-e663-476d-a46f-50031e4869f9"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
