# Generated by Django 5.1.6 on 2025-02-24 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0003_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("dff5c29a-220c-4f09-8c22-993d018f408d"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
