# Generated by Django 5.1.6 on 2025-02-24 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("697016b0-6f79-489e-95e8-4fc94bde7adf"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
